name: dual_clash
description: Dual Clash
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.3
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  # one global image for all platforms
  image_path: "assets/application/icon_1024x1024.png"

  # mobile
  ios: true
  android: "launcher_icon"
  min_sdk_android: 21
  # Desktop/Web (each requires a map, not a boolean)
  windows:
    generate: true
    image_path: "assets/application/icon_1024x1024.png"
    # optional: 48â€“256, default 48
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/application/icon_1024x1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
          weight: 700
