name: dual_clash
description: Dual Clash
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.3
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  flutter_svg: ^2.0.10
  just_audio: ^0.9.39
  window_manager: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  # one global image for all platforms
  image_path: "assets/application/icon_1024x1024.png"

  # mobile
  ios: true
  android: "launcher_icon"
  min_sdk_android: 21
  # Desktop/Web (each requires a map, not a boolean)
  windows:
    generate: true
    image_path: "assets/application/icon_1024x1024.png"
    # optional: 48â€“256, default 48
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/application/icon_1024x1024.png"
  web:
    generate: true
    image_path: "assets/application/icon_1024x1024.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/achievements/
    - assets/icons/campaigns/
    - assets/icons/languages/
    - assets/icons/menu/
    - assets/icons/
    - assets/m4a/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
