name: dual_clash
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.3
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  ios: true
  android: true
  windows: true
  image_path: "assets/ipad/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
          weight: 700
